#include <sstream>
#include <string>
#include <fstream>
#include <iomanip>
#include <vector>
#include <map>
#include <algorithm>
#include <functional>
#include <cmath>
#include <iostream>
#include <bitset>
#include <complex>
#include <memory>


#include "TH1F.h"
#include "TF1.h"
#include "TH2F.h"
#include "TCanvas.h"
#include "TFile.h"
#include "TLine.h"
#include "TProfile.h"
#include "TError.h"
#include "TNtuple.h"
#include "TVector.h"
#include "TGraph.h"
#include "TGraphErrors.h"
#include "TMultiGraph.h"
#include "TPad.h"
#include "TGaxis.h"
#include "TAttLine.h"
#include "TApplication.h"
#include "THStack.h"
#include <TGClient.h>
#include <TF1.h>
#include "TTree.h"
#include "TBranch.h"
#include "TChain.h"
#include <TRandom.h>
#include <TGButton.h>
#include <TGFrame.h>
#include <TROOT.h>
#include "TStyle.h"
#include "TTreeViewer.h"
#include "TLegend.h"
#include "TLatex.h"
#include "TPaveStats.h"
#include <TRootEmbeddedCanvas.h>
#include <RQ_OBJECT.h>
#include <TMatrixDSym.h>
#include <TFitResultPtr.h>
#include <TFitResult.h>
#include <TMinuit.h>
